config/routes.rb
Rails.application.routes.draw do
  root to: "restaurants#index"
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: [:index, :show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  CATEGORY = ["Chinese", "Italian", "Japanese", "French", "Belgian", "Brazilian"]

  validates :category, presence: true, inclusion: { in: CATEGORY }
  validates :name, presence: true
  validates :category, presence: true
  validates :address, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[ show edit update destroy ]

  # GET /restaurants or /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1 or /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants or /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to restaurant_url(@restaurant), notice: "Restaurant was successfully created." }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1 or /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to restaurant_url(@restaurant), notice: "Restaurant was successfully updated." }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1 or /restaurants/1.json
  def destroy
    @restaurant.destroy
    redirect_to root_path, notice: "Restaurant was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :phone_number, :category)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[new create]

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @parmas = review_params
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant

    respond_to do |format|
      if @review.save
        format.html { redirect_to restaurant_url(@restaurant), notice: "Review was successfully created." }
        @review.save
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end

  end

  def index
    @reviews = Review.all
  end

  def show
    @reviews = Review.where(restaurant_id: params[:id])
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <%= f.input :name, class: "form-control"  %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: Restaurant::CATEGORY%>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/restaurants/_restaurant.html.erb
<div class="card"  id="<%= dom_id restaurant %>">
  <div class="card-body">

    <% if current_page?("/") %>
      <div class="d-flex align-items-baseline">
        <h5 class="card-title me-2">Name:</h5>
        <p class="card-text">
          <%= restaurant.name %>
        </p>
      </div>
    <% end %>

    <div class="d-flex align-items-baseline">
      <h5 class="card-title me-2">Address:</h5>
      <p class="card-text">
        <%= restaurant.address %>
      </p>
    </div>

    <div class="d-flex align-items-baseline">
      <h5 class="card-title me-2">Phone number:</h5>
      <p class="card-text">
        <%= restaurant.phone_number %>
      </p>
    </div>

    <div class="d-flex align-items-baseline">
      <h5 class="card-title me-2">Category:</h5>
      <p class="card-text">
        <%= restaurant.category %>
      </p>
    </div>

    <% if current_page?("/") %>
      <%=  link_to "Show this restaurant", restaurant, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/restaurants/edit.html.erb
<div class="container">
  <h1>Editing restaurant</h1>

  <%= render "form", restaurant: @restaurant %>

  <%= link_to "Back to #{@restaurant.name}", @restaurant, class: "btn btn-secondary mt-2" %>
</div>

app/views/restaurants/index.html.erb
<div class="container p-3">
  <p style="color: green"><%= notice %></p>

  <h1>Restaurants</h1>

  <%= link_to "New restaurant", new_restaurant_path, class: "btn btn-primary" %>
  <%= link_to "All reviews", reviews_path, class: "btn btn-primary" %>

  <div class="card my-3" id="restaurants">
    <% @restaurants.each do |restaurant| %>
      <div class="card-body">
        <%= render restaurant %>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <h1>New restaurant</h1>

  <%= render "form", restaurant: @restaurant %>

  <%= link_to "Back to restaurants", root_path, class: "btn btn-secondary mt-2" %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <%= link_to "Back to restaurants", root_path, class: "btn btn-secondary mb-3"%>
  <h1 class="mt-3"><%= @restaurant.name %></h1>

  <%= render @restaurant %>

  <div class="d-flex justify-content-between mt-3">
    <div class="mb-2">
      <%= link_to "New review", new_restaurant_review_path(@restaurant), class: "btn btn-info" %>
      <%= link_to "Reviews", review_path(@restaurant), class: "btn btn-dark" %>
    </div>
    <div class="d-flex">
      <%= link_to "Edit", edit_restaurant_path(@restaurant), class: "btn btn-warning me-2" %>
      <%= link_to "Destroy", restaurant_path(@restaurant), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger" %>
    </div>
  </div>
</div>

app/views/reviews/index.html.erb
<div class="container mt-5">
  <h1>All reviews</h1>
  <%= link_to "Back to restaurants", root_path, class: "btn btn-secondary mb-3"%>
  <div class="card">
    <% @reviews.each do |review|%>
      <div class="card-body">
        <div class="card">
          <div class="p-2">
            <h5 class="card-title"><%= review.restaurant.name %></h5>
            <p class="card-text">
              <strong>Rating:</strong>
              <%= review.rating %>/5
            </p>
            <p class="card-text">
              <strong>Content:</strong>
              <%= review.content %>
            </p>
            <%= link_to "Go to #{review.restaurant.name}", review.restaurant, class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <h1>New review to <%= @restaurant.name %></h1>
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content, label: "Review" %>
    <%= f.input :rating, :collection => 0..5 %>
    <%= @parmas %>
    <%= f.submit "Submit review", class: "btn btn-primary" %>
  <% end %>
  <%= link_to "Back to #{@restaurant.name}", restaurant_path(@restaurant), class: "btn btn-secondary mt-2"%>
</div>

app/views/reviews/show.html.erb
<div class="container p-3 mt-2">
  <% if @reviews.empty? %>
    <h1> Não exite reviews</h1>
    <%= link_to "Back to restaurants", root_path, class: "btn btn-secondary btn-sm mb-3" %>
  <% else %>
    <h1><%= @reviews[0].restaurant.name %> - Reviews</h1>
    <%= link_to "Back to #{@reviews[0].restaurant.name}", restaurant_path(@reviews[0].restaurant), class: "btn btn-primary btn-sm mb-3" %>
    <% @reviews.each do |review| %>
      <div class="card mb-2">
        <div class="card-body">
          <div class="d-flex align-items-baseline">
            <h5 class="card-title me-2">Rating:</h5>
            <p class="card-text">
              <%= review.rating %>/5
            </p>
          </div>

          <div class="d-flex align-items-baseline">
            <h5 class="card-title me-2">Review:</h5>
            <p class="card-text">
              <%= review.content %>
            </p>
          </div>

        </div>
      </div>
    <% end %>
  <% end %>
</div>